version: "3.9"
services:
  redis-storage:
    image: redis/redis-stack:latest
    container_name: 'redis-storage'
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-storage-data:/data

volumes:
  redis-storage-data:
    driver: local
